name: ASP.NET Core CI

on:
  push:
    branches: [ main, dev-rajdip ]
  pull_request:
    branches: [ main, dev-rajdip ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore ./src/UniversityEvents.Web/UniversityEvents.Web.csproj

    - name: Build projects
      run: dotnet build ./src/UniversityEvents.Web/UniversityEvents.Web.csproj --configuration Release --no-restore

    - name: Run unit tests
      run: dotnet test ./tests/UniversityEvents.UnitTests/UniversityEvents.UnitTests.csproj \
            --no-build \
            --logger "trx;LogFileName=test_results.trx"

    - name: Publish app
      run: dotnet publish ./src/UniversityEvents.Web/UniversityEvents.Web.csproj \
            -c Release -o ./publish

    - name: Upload app artifact
      uses: actions/upload-artifact@v4
      with:
        name: aspnetcore-app
        path: ./publish

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: './tests/UniversityEvents.UnitTests/TestResults/*.trx'
